const {calculateRoute} = require('../route');
const {getItems} = require('../recipe');
const {calculateProfit} = require("../profit");
const {calculateCraftingPrice} = require("../price");

const list = [
  "Living Arch",
  "Regal Letter Box",
  "Varied Wood Flooring",
  "Tatami Flooring",
  "Varied Wood Interior Wall",
  "Garden Pond",
  "Large Planter Box",
  "Oriental Grass Plot",
  "Shishi-odoshi",
  "Planter Partition",
  "Deluxe Manor Fireplace",
  "Woodland Chair",
  "Manor Stool",
  "Sylphic Table",
  "Manor Table",
  "Imitation Wooden Skylight",
  "Imitation Stained Crystal Pane",
  "Sheep Rug",
  "Table Orchestrion",
  "Crystal Bell",
  "Summoning Bell",
  "Armoire",
  "Company Chest",
  "Toy Box",
  "The Unending Journey",
  "Projection Module",
  "Goobbue Rug",
  "Living Arch",
  "Regal Letter Box",
  "Varied Wood Flooring",
  "Tatami Flooring",
  "Varied Wood Interior Wall",
  "Garden Pond",
  "Large Planter Box",
  "Oriental Grass Plot",
  "Shishi-odoshi",
  "Planter Partition",
  "Deluxe Manor Fireplace",
  "Woodland Chair",
  "Manor Stool",
  "Sylphic Table",
  "Manor Table",
  "Imitation Wooden Skylight",
  "Imitation Stained Crystal Pane",
  "Sheep Rug",
  "Table Orchestrion",
  "Crystal Bell",
  "Summoning Bell",
  "Armoire",
  "Company Chest",
  "Toy Box",
  "The Unending Journey",
  "Projection Module",
  "Goobbue Rug",
  "Roof Tile",
  "Riviera Cottage Roof (Wood)",
  "Riviera Cottage Roof (Composite)",
  "Riviera Cottage Roof (Stone)",
  "Riviera House Roof (Wood)",
  "Riviera House Roof (Composite)",
  "Riviera House Roof (Stone)",
  "Riviera Mansion Roof (Wood)",
  "Riviera Mansion Roof (Composite)",
  "Riviera Mansion Roof (Stone)",
  "Glade Cottage Roof (Wood)",
  "Glade Cottage Roof (Composite)",
  "Glade Cottage Roof (Stone)",
  "Glade House Roof (Wood)",
  "Glade House Roof (Composite)",
  "Glade House Roof (Stone)",
  "Glade Mansion Roof (Wood)",
  "Glade Mansion Roof (Composite)",
  "Glade Mansion Roof (Stone)",
  "Oasis Cottage Roof (Wood)",
  "Oasis Cottage Roof (Composite)",
  "Oasis Cottage Roof (Stone)",
  "Oasis House Roof (Wood)",
  "Oasis House Roof (Composite)",
  "Oasis House Roof (Stone)",
  "Oasis Mansion Roof (Wood)",
  "Oasis Mansion Roof (Composite)",
  "Oasis Mansion Roof (Stone)",
  "Riviera Cottage Wall (Wood)",
  "Riviera Cottage Wall (Composite)",
  "Riviera Cottage Wall (Stone)",
  "Riviera House Wall (Wood)",
  "Riviera House Wall (Composite)",
  "Riviera House Wall (Stone)",
  "Riviera Mansion Wall (Wood)",
  "Riviera Mansion Wall (Composite)",
  "Riviera Mansion Wall (Stone)",
  "Glade Cottage Wall (Wood)",
  "Glade Cottage Wall (Composite)",
  "Glade Cottage Wall (Stone)",
  "Glade House Wall (Wood)",
  "Glade House Wall (Composite)",
  "Glade House Wall (Stone)",
  "Glade Mansion Wall (Wood)",
  "Glade Mansion Wall (Composite)",
  "Glade Mansion Wall (Stone)",
  "Oasis Cottage Wall (Wood)",
  "Oasis Cottage Wall (Composite)",
  "Oasis Cottage Wall (Stone)",
  "Oasis House Wall (Wood)",
  "Oasis House Wall (Composite)",
  "Oasis House Wall (Stone)",
  "Oasis Mansion Wall (Wood)",
  "Oasis Mansion Wall (Composite)",
  "Oasis Mansion Wall (Stone)",
  "Riviera Arched Window",
  "Riviera Bay Window",
  "Riviera Oblong Window",
  "Glade Classical Window",
  "Glade Rounded Window",
  "Glade Lancet Window",
  "Oasis Oblong Window",
  "Oasis Lancet Window",
  "Oasis Octagonal Window",
  "Riviera Wooden Door",
  "Riviera Studded Door",
  "Riviera Ornate Door",
  "Glade Classical Door",
  "Glade Lancet Door",
  "Glade Arched Door",
  "Oasis Arched Door",
  "Oasis Crowned Door",
  "Oasis Classical Door",
  "Riviera Rounded Chimney",
  "Riviera Stone Chimney",
  "Glade Thatch Chimney",
  "Glade Rounded Chimney",
  "Oasis Stone Chimney",
  "Oasis Rounded Chimney",
  "Riviera Wooden Awning",
  "Riviera Awning",
  "Glade Tiled Awning",
  "Glade Awning",
  "Oasis Wooden Awning",
  "Oasis Awning",
  "Riviera Wall Chimney",
  "Glade Wall Chimney",
  "Oasis Wall Chimney",
  "Riviera Roofed Wall",
  "Riviera Picket Wall",
  "Riviera Stone Wall",
  "Glade Cobblestone Wall",
  "Glade Thatch Wall",
  "Glade Roundpole Fence",
  "Oasis Wooden Wall",
  "Oasis Stone Wall",
  "Oasis Ornate Fence",
  "Riviera Interior Wall",
  "Glade Interior Wall",
  "Oasis Interior Wall",
  "Riviera Flooring",
  "Glade Flooring",
  "Oasis Flooring",
  "Riviera Pendant Lamp",
  "Deluxe Riviera Pendant Lamp",
  "Riviera Chandelier",
  "Glade Pendant Lamp",
  "Deluxe Glade Pendant Lamp",
  "Glade Chandelier",
  "Oasis Pendant Lamp",
  "Deluxe Oasis Pendant Lamp",
  "Oasis Chandelier",
  "Morbol Chandelier",
  "Walnut Table",
  "Mythril Table",
  "Riviera Lamppost",
  "Stump Stool",
  "Cragsoul Lamp",
  "Titanic Cragsoul Lamp",
  "Riviera Chair",
  "Glade Chair",
  "Oasis Chair",
  "Morbol Chair",
  "Ahriman Chair",
  "Sylphic Chair",
  "Manor Highback Chair",
  "Knight Captain's Chair",
  "Riviera Armchair",
  "Glade Armchair",
  "Oasis Armchair",
  "Riviera Bed",
  "Glade Bed",
  "Oasis Bed",
  "Ash Cabinet",
  "Riviera Wardrobe",
  "Glade Wardrobe",
  "Oasis Wardrobe",
  "Manor Wardrobe",
  "Riviera Cupboard",
  "Glade Cupboard",
  "Oasis Cupboard",
  "Manor Cupboard",
  "Ahriman Cupboard",
  "Sylphic Cupboard",
  "Riviera Bookshelf",
  "Glade Bookshelf",
  "Oasis Bookshelf",
  "Manor Bookshelf",
  "Ahriman Bookshelf",
  "Sylphic Bookshelf",
  "Morbol Bookshelf",
  "Riviera Pillar",
  "Glade Pillar",
  "Oasis Pillar",
  "Riviera Partition",
  "Glade Partition",
  "Oasis Partition",
  "Mahogany Screen",
  "Ahriman Screen",
  "Sylphic Screen",
  "Morbol Screen",
  "Riviera Floor Lamp",
  "Glade Floor Lamp",
  "Oasis Floor Lamp",
  "Tonberry Floor Lamp",
  "Mandragora Floor Lamp",
  "Amigo Cactus Floor Lamp",
  "Riviera Bathtub",
  "Glade Bathtub",
  "Oasis Bathtub",
  "Terracotta Pot",
  "Potted Maguey",
  "Vodoriga Sculpture",
  "Gargoyle Sculpture",
  "Riviera Round Table",
  "Oasis Round Table",
  "Glade Round Table",
  "Ahriman Round Table",
  "Riviera Table",
  "Glade Table",
  "Oasis Table",
  "Riviera Dining Table",
  "Glade Dining Table",
  "Oasis Dining Table",
  "Walnut Dining Table",
  "Sylphic Dining Table",
  "Glade Drawer Table",
  "Riviera Stall",
  "Glade Stall",
  "Oasis Stall",
  "Potted Axilflower",
  "Potted Azalea",
  "Potted Spider Plant",
  "Table Chronometer",
  "Demon Wall Sculpture",
  "Inferno Wall Lamp",
  "Blazing Inferno Wall Lamp",
  "Sylphic Wall Lantern",
  "Nymian Wall Lantern",
  "Amdapori Wall Lantern",
  "Wall Chronometer",
  "Behemoth Wall Trophy",
  "Riviera Rug",
  "Riviera Fringed Rug",
  "Riviera Oval Rug",
  "Glade Rug",
  "Glade Fringed Rug",
  "Glade Blossom Rug",
  "Oasis Rug",
  "Oasis Argyle Rug",
  "Oasis Leaf Rug",
  "Moogle Rug",
  "Morbol Rug",
  "Riviera Table Chronometer",
  "Glade Wall Chronometer",
  "Tonberry Round Table",
  "Tonberry Dining Table",
  "Tonberry Armchair",
  "Tonberry Bookshelf",
  "Tonberry Bed",
  "Tonberry Screen",
  "Tonberry Wall Lantern",
  "Tonberry Oval Rug",
  "Lalafellin Step Stool",
  "Carbuncle Round Table",
  "Carbuncle Armchair",
  "Carbuncle Chair",
  "Carbuncle Wardrobe",
  "Carbuncle Rug",
  "Looming Tonberry Screen",
  "Tonberry Square Rug",
  "Eorzean Map Table",
  "Manor Music Stool",
  "Carbuncle Garden Table",
  "Country Interior Wall",
  "Stone Interior Wall",
  "Tiled Interior Wall",
  "Metal Interior Wall",
  "Arbor Interior Wall",
  "Chocobo Interior Wall",
  "Moogle Interior Wall",
  "Country Flooring",
  "Stone Flooring",
  "Tiled Flooring",
  "Metal Flooring",
  "Arbor Flooring",
  "Chocobo Flooring",
  "Moogle Flooring",
  "Tonberry Chandelier",
  "Magicked Stable Broom",
  "Riviera Wall Shelf",
  "Wall Planter",
  "Riviera Half Partition",
  "Potted Umbrella Fig",
  "Potted Dragon Tree",
  "Plasma Lamp",
  "Lord of Levin Lamp",
  "Riviera Doormat",
  "Double Feather Bed",
  "Chocobo Pillar",
  "Cast-iron Cookpot",
  "Glade Hedgewall",
  "Oasis Fence",
  "Riviera Fence",
  "Riviera Flora Interior Wall",
  "Glade Flora Interior Wall",
  "Oasis Flora Interior Wall",
  "Classic Interior Wall",
  "Striped Interior Wall",
  "Mosaic Interior Wall",
  "Bisque Flooring",
  "Marble Flooring",
  "Ceramic Tile Flooring",
  "South Seas Armchair",
  "Riviera Canopy Bed",
  "Glade Canopy Bed",
  "Oasis Canopy Bed",
  "Potted Oliphant's Ear",
  "Riviera Stool",
  "Glade Stool",
  "Oasis Stool",
  "Riviera Open-shelf Bookcase",
  "Glade Open-shelf Bookcase",
  "Oasis Open-shelf Bookcase",
  "Wall Lantern",
  "Glade Doormat",
  "Oasis Doormat",
  "Large Woven Rug",
  "Glade Lamppost",
  "Oasis Lamppost",
  "Masonwork Interior Wall",
  "Masonwork Flooring",
  "Checkered Flooring",
  "Iron Plate Flooring",
  "Ice Chandelier",
  "Diamond Chandelier",
  "Oriental Bathtub",
  "Kotatsu Table",
  "Wax Vegetables",
  "Royal Partition",
  "Riviera Garden Table Set",
  "Spotted Interior Wall",
  "Wavy Interior Wall",
  "Monochrome Flooring",
  "Oasis Cobble Flooring",
  "Star Chandelier",
  "Alpine Chair",
  "Alpine Round Table",
  "Glade Half Partition",
  "Oasis Half Partition",
  "Cask Rack",
  "Royal Plotting Table",
  "Round Banquet Table",
  "Stained Crystal Interior Wall",
  "Wyvernskin Pot Helm of Maiming",
  "Oriental Round Table",
  "Funguar Chair",
  "Mahogany Partition Door",
  "Cob Inner Wall",
  "Manor Flooring",
  "Alpine Chandelier",
  "Alpine Flooring",
  "Alpine Inner Wall",
  "Sharlayan Flooring",
  "Bluesky Interior Wall",
  "Mounted Box Shelf",
  "Mounted Bookshelf",
  "Combed Wool Rug",
  "Paissa Floor Lamp",
  "Merchant's Shelf",
  "Ivy Pillar",
  "Pendant Lamp Planter",
  "Gyuki Leather Pot Helm",
  "Carbuncle Bed",
  "Doman Partition",
  "Hingan Cottage Roof (Mokuzo)",
  "Hingan Cottage Roof (Nanpu)",
  "Hingan Cottage Roof (Kura-zukuri)",
  "Hingan House Roof (Mokuzo)",
  "Hingan House Roof (Nanpu)",
  "Hingan House Roof (Kura-zukuri)",
  "Hingan Mansion Roof (Mokuzo)",
  "Hingan Mansion Roof (Nanpu)",
  "Hingan Mansion Roof (Kura-zukuri)",
  "Hingan Cottage Wall (Mokuzo)",
  "Hingan Cottage Wall (Nanpu)",
  "Hingan Cottage Wall (Kura-zukuri)",
  "Hingan House Wall (Mokuzo)",
  "Hingan House Wall (Nanpu)",
  "Hingan House Wall (Kura-zukuri)",
  "Hingan Mansion Wall (Mokuzo)",
  "Hingan Mansion Wall (Nanpu)",
  "Hingan Mansion Wall (Kura-zukuri)",
  "Hingan Oblong Window",
  "Hingan Lancet Window",
  "Hingan Squinch Window",
  "Hingan Door (Mokuzo)",
  "Hingan Door (Nanpu)",
  "Hingan Door (Kura-zukuri)",
  "Hingan Chimney (Kura-zukuri)",
  "Hingan Awning (Mokuzo)",
  "Hingan Awning (Nanpu)",
  "Hingan Awning (Kura-zukuri)",
  "Hingan Fence (Mokuzo)",
  "Hingan Fence (Nanpu)",
  "Hingan Fence (Kura-zukuri)",
  "Hingan Interior Wall",
  "Hingan Flooring",
  "Hingan Hanging Bonbori Lamp",
  "Hingan Hanging Andon Lamp",
  "Hingan Hanging Toro Lamp",
  "Hingan Chair",
  "Hingan Bed",
  "Hingan Bookshelf",
  "Hingan Cupboard",
  "Hingan Open-shelf Bookcase",
  "Paper Partition",
  "Corner Hedge Partition",
  "Hedge Partition",
  "Redoubtable Rolanberry Tart",
  "Imitation Shuttered Window",
  "Mahogany Bunk Bed",
  "Mounted Plate Rack",
  "Bathroom Floor Tiles",
  "Bathroom Wall Tiles",
  "Small Imitation Window",
  "White Rectangular Partition",
  "Marimo Lamp",
  "Red Carpet",
  "Hanging Planter Shelf",
  "Teal Blue Carpeting",
  "Black-and-white Interior Wall",
  "Altered Boarskin Pot Helm",
  "Walnut Interior Wall",
  "Brick Flooring",
  "Crystarium Chandelier",
  "Lily Floor Lamp",
  "Lily Wall Lamp",
  "Crystarium Teapot",
  "Eulmoran Inner Wall",
  "Eulmoran Marble Flooring",
  "Eulmoran Chandelier",
  "Oasis Wall-mounted Fountain",
  "Imitation Long Window",
  "Tabletop Hat Stand",
  "Lakeland Chair",
  "Lakeland Table",
  "Armorer's Stall",
  "Weaponsmith's Stall",
  "Jeweler's Stall",
  "Florist's Stall",
  "Baker's Stall",
  "Fruiterer's Stall",
  "Greengrocer's Stall",
  "Bookseller's Stall",
  "Enchanter's Stall",
  "Butcher's Stall",
  "Vegetable Garden",
  "Indoor Oriental Garden",
  "Rough Stone Interior Wall",
  "Rough Stone Flooring",
  "Wooden Chandelier",
  "Dish Rack",
  "Oldrose Wall Planter",
  "First Chair's Trumpet",
  "Used Banquet Table",
  "Steppe Bed",
  "Fat Cat Wall Chronometer",
  "Brick Garden Wall",
  "Manor Dressing Table",
  "Ronkan Rocking Chair",
  "Factory Interior Wall",
  "Factory Flooring",
  "Factory Chandelier",
  "Wooden Staircase Bookshelf",
  "Floor Sofa",
  "Barrel Table",
  "Indoor Pond",
  "Factory Automatic Door",
  "Factory Partition",
  "Factory Wall Lamp",
  "Marble Alcove Bed",
  "Wood Slat Partition",
  "Paissa Swing Chair",
  "Shakshouka Pot",
  "Herringbone Flooring",
  "Skylight Chandelier",
  "Toymaker's Show Window",
  "Designer's Show Window",
  "Smith's Show Window",
  "Artist's Show Window",
  "Baker's Show Window",
  "Storm Blue Interior Wall",
  "Cream Yellow Carpet",
  "Cloud Acorn Chandelier",
  "Eastern Indoor Pond",
  "Wooden Reel Table",
  "Windowed Partition",
  "Hingan Windowed Partition",
  "Philosopher's Stone Table",
  "Crystarium Wardrobe",
  "Low Bookshelf",
  "Qiqirn Shelf",
  "Bar Rack",
  "Goobbue Wall Chronometer",
  "Garden Tool Shelf",
  "Materiel Table",
  "Sykon Compote",
  "Garlean Concrete Inner Wall",
  "Leafy Ceiling Lamp",
  "Indoor Oriental Waterfall",
  "Apothecary's Workbench",
  "Pendant Wall Light",
  "Square Niche Partition",
  "Fat Cat Rug",
  "Loft Bed",
  "Shoe Rack",
  "Lamp Component",
  "Gordian Chair",
  "Savage Gordian Chair",
  "Bearskin Rug",
  "Faerie Chandelier",
  "Pudding Floor Lamp",
  "Pudding Throw Rug",
  "Tablet Supplies",
  "Wall Repair Supplies",
  "Staggered Shelf",
  "Beach Chair",
  "Knightly Round Table",
  "Great Gubal Floor Lamp",
  "Indirect Wall Lighting",
  "Crystal Chandelier",
  "Fortemps Manor Interior Wall",
  "Tribunal Flooring",
  "Ornate Partition",
  "Potent Dissolvent",
  "House Fortemps Chandelier",
  "Flying Chair",
  "Imitation Square Window",
  "Moogle Wall Chronometer",
  "Mounted Cupboard",
  "Carbuncle Bathtub",
  "House Borel Interior Wall",
  "Classic Chandelier",
  "Solid-brick Interior Wall",
  "Unfinished Wood Flooring",
  "Odder Otter Hanging Andon Lamp",
  "Merry Mog Bed",
  "Mellow Mog Lamp",
  "Odder Otter Dining Table",
  "Odder Otter Screen",
  "Odder Otter Chair",
  "Odder Otter Wall Lantern",
  "Portable Stepladder",
  "Bar Stool",
  "Jellyfish Lamp",
  "Grand Chair",
  "Odder Otter Andon Lamp",
  "Glade Partition Door",
  "Oasis Partition Door",
  "Suzaku Wall Hanging",
  "Bread Rack",
  "Carpeting",
  "Unfinished Interior Wall",
  "Mirific Mogshelf",
  "Carbuncle Chandelier",
  "Magicked Bed",
];
const expensiveFurniture = [
  "Sheep Rug",
  "Sylphic Table",
  "Sylphic Dining Table",
  "Planter Partition",
  "Regal Letter Box",
  "The Unending Journey",
  "Summoning Bell",
  "Large Planter Box",
  "Moogle Letter Box",
  "Company Chest",
  "Woodland Chair",
  "Living Arch",
  "Varied Wood Interior Wall",
  "Tatami Flooring",
  "Toy Box",
  "Imitation Wooden Skylight",
  "Varied Wood Flooring",
  "Shishi-odoshi",
  "Deluxe Manor Fireplace",
  "Oriental Grass Plot",
  "Imitation Stained Crystal Pane",
  "Manor Stool",
  "Garden Pond",
  "Manor Table",
];
const it = [
  "Planter Partition",
  "Moogle Letter Box",
  "Summoning Bell",
  "Deluxe Manor Fireplace",
  "Large Planter Box",
  "Regal Letter Box",
  "Hingan Cleaning Supplies",
  "Odder Otter Wall Lantern",
];

async function bootstrap() {
  const items = getItems(["Deluxe Manor Fireplace"]);
  const amount = 5;
  items.forEach(i => i.amount = amount);

  const profits = (await calculateProfit(items, {minimumProfit: 10000, minimumVelocity: 8})).slice(0, 5);
  const shoppingList = [];
  for (const profit of profits) {
    shoppingList.push(await calculateCraftingPrice({id: profit.crafted.id, name: profit.crafted.name, amount}));
  }
  await calculateRoute(shoppingList);
}


bootstrap();