const { calculateRoute } = require('../route');
const { getItems } = require('../src/entity/recipe');
const { calculateProfit } = require("../src/profit");
const { calculateCraftingPrice } = require("../src/market");

const skybuilderScrips = [
  "Grade 4 Skybuilders' Brazier",
  "Grade 4 Skybuilders' Lamppost"
];

const fashionItems = [
  "High House Halfboots",
  "High House Boots",
  "Rebel Boots",
];

const supplies = [
  "Grade 6 Tincture of Strength",
  "Grade 6 Tincture of Intelligence",
  "Grade 6 Tincture of Vitality",
  "Grade 6 Tincture of Dexterity",
  "Archon Burger",
  "Beef Stroganoff",
  "Pumpkin Ratatouille",
  "Pumpkin Potage",
  "Peach Juice",
  "Peach Tart",
  "Sykon Cookie",
  "Thavnairian Chai",
  "Scallop Salad",
  "Scallop Curry",
];

const niceSupplies = [
  "Grade 6 Tincture of Strength",
  "Pumpkin Potage",
  "Grade 6 Tincture of Dexterity",
  "Grade 6 Tincture of Intelligence",
];

const craftSupplies = [
  "Cunning Craftsman's Draught",
  "Tsai tou Vounou"
];

const slayingItems = [
  "Classical Earrings of Slaying",
  "Classical Ring of Slaying",
  "Classical Wristband of Slaying",
  "Classical Choker of Slaying",
];

const levelOnes = [
  "Paladin's Hades Arms",
  "Company Tabard",
  "Hades Barding",
  "Boulevardier's Ruffled Shirt",
  "Urban Coat",
  "Rebel Coat",
  "Rebel Boots",
  "Urban Boots",
  "Magicked Bed",
  "Company Hat",
  "Crescent Moon Nightgown",
  "Company Escutcheon",
  "Calfskin Rider's Jacket",
  "Frontier Jacket",
  "Calfskin Rider's Bottoms",
  "True Barding of Light",
  "Crescent Moon Slippers",
  "Ao Dai",
  "Cashmere Poncho",
  "Titania Barding",
  "Frontier Trousers",
  "Boulevardier's Ruffled Pantaloons",
  "Suzaku's Flame-kissed Arms",
  "Summer Indigo Shirt",
  "Byakko's Enspirited Arms",
  "Tsukuyomi's Moonlit Arms",
  "Crescent Moon Cone",
  "Shinryu's Ephemeral Arms",
  "Barding of Divine Light",
  "Quan",
  "Thavnairian Gloves",
  "Taoist's Shirt",
  "Frontier Dress",
  "Calfskin Rider's Cap",
  "Spring Dress",
  "Coeurl Beach Halter",
  "Seiryu's Sanctified Arms",
  "Calfskin Rider's Shoes",
  "Coeurl Beach Briefs",
  "Spring Skirt",
  "Diamond Barding",
  "Taoist's Slops",
  "A World Apart Orchestrion Roll",
  "Quaintrelle's Ruffled Skirt",
  "Coeurl Beach Tanga",
  "Frontier Pumps",
  "Calfskin Rider's Gloves",
  "Non La",
  "Shaded Spectacles",
  "Frontier Dress Gloves",
  "Frontier Ribbon",
  "Hannish Wool Autumn Shirt",
  "Eternal Wind - Shadowbringers Orchestrion Roll",
  "Boulevardier's Hat",
  "Thavnairian Wool Autumn Shirt",
  "Suzaku Barding",
  "Southern Seas Trousers",
  "Shinryu Barding",
  "Lunar Barding",
  "Replica Sky Pirate's Vest of Aiming",
  "Emerald Barding",
  "Barding of Eternal Darkness",
  "Hooded Fireglass Leather Vest",
  "Paladin's Arms of the Round",
  "Thavnairian Bustier",
  "Southern Seas Shirt",
  "Thavnairian Armlets",
  "Paladin's Goddess Arms",
  "Thavnairian Tights",
  "Thavnairian Sandals",
  "Replica Sky Pirate's Boots of Aiming",
  "Answers Orchestrion Roll",
  "Paladin's Horde Arms",
  "Crescent Moon Bottoms",
  "Ruby Barding",
  "Sailor Shirt",
  "Southern Seas Skirt",
  "Steam-powered Gobwalker G-VII",
  "Replica Sky Pirate's Boots of Fending",
  "Plain Long Skirt",
  "Replica Sky Pirate's Jacket of Scouting",
  "Seiryu Barding",
  "Byakko Barding",
  "Thunderer Orchestrion Roll",
  "Paladin's Endless Expanse Arms",
  "Frontier Shoes",
  "Boulevardier's Dress Shoes",
  "Rise of the White Raven Orchestrion Roll",
  "Dalmascan Draped Top",
  "Starved Orchestrion Roll",
  "Quaintrelle's Ruffled Dress",
  "Innocence Barding",
  "Cropped Fireglass Leather Slops",
  "Replica Sky Pirate's Jacket of Striking",
  "Replica Sky Pirate's Mask of Scouting",
  "Paladin's Demon Arms",
  "Frontier Hat",
  "Odder Otter Hanging Andon Lamp",
  "Hose of Happiness",
  "Odder Otter Wall Lantern",
  "Replica Sky Pirate's Coat of Fending",
  "Coeurl Talisman",
  "Light Steel Galerus",
  "Thavnairian Headdress",
  "Flying Chair",
  "Adventurer's Hooded Vest",
  "Dalmascan Draped Bottoms",
  "To the Edge Orchestrion Roll",
  "Replica Sky Pirate's Mask of Striking",
  "Hingan Cleaning Supplies",
  "Coeurl Beach Pareo",
  "Odder Otter Andon Lamp",
  "Light Steel Subligar",
  "Boots of Happiness",
  "Crescent Moon Nightcap",
  "The Silent Regard of Stars Orchestrion Roll",
  "Thavnairian Wool Autumn Dress",
  "Whisperfine Woolen Coat",
  "Blood for Blood Orchestrion Roll",
  "Paladin's Dead Hive Arms",
  "Suzaku Wall Hanging",
  "Expeditioner's Thighboots",
  "Minstrel's Spectacles",
  "Engage Orchestrion Roll",
  "Sophic Barding",
  "Wristlet of Happiness",
  "Replica Sky Pirate's Boots of Scouting",
  "Replica Sky Pirate's Bottoms of Casting",
  "Model Magitek Bit",
  "Cape of Happiness",
  "Cashmere Hood",
  "Magic Broom",
  "Lost in the Clouds Orchestrion Roll",
  "Whisperfine Woolen Shorts",
  "Sailor Brais",
  "Sewing Baskets",
  "Dalmascan Leather Shoes",
  "From the Ashes Orchestrion Roll",
  "Mellow Mog Lamp",
  "Reveler's Barding",
  "Expeditioner's Pantalettes",
  "High House Justaucorps",
  "Close to the Heavens Orchestrion Roll",
  "Taffeta Loincloth",
  "Against the Wind Orchestrion Roll",
  "Iron Dwarf",
  "Quaintrelle's Hat",
  "Replica Sky Pirate's Coat of Casting",
  "Taffeta Shawl",
  "Moonfire Tanga",
  "Pink Cherry Blossom Corsage",
  "Blissful Barding",
  "Amatsu Kaze Orchestrion Roll",
  "Merry Mog Bed",
  "Odder Otter Bench",
  "Moonfire Sandals",
  "Coeurl Beach Maro",
  "Replica Sky Pirate's Beret of Aiming",
  "Wind Silk Coatee",
  "Orthodox Barding",
  "Levin Barding",
  "Whisperfine Woolen Boots",
  "Answer on High Orchestrion Roll",
  "Spring Dress Shoes",
  "Replica Sky Pirate's Boots of Striking",
  "Wind-up Illuminatus",
  "Replica Sky Pirate's Bottoms of Healing",
  "Clockwork Barrow",
  "Replica Sky Pirate's Coat of Healing",
  "Skylords Orchestrion Roll",
  "Ala Mhigan Gown",
  "White Triteleia Earring",
  "Southern Kitchen",
  "Paladin's Fiend Arms",
  "Plush Cushion",
  "Odder Otter Dining Table",
  "Odder Otter Screen",
  "Paladin's Levin Arms",
  "Ice Barding",
  "Highland Barding",
  "Black and White Orchestrion Roll",
  "Bar Counter",
  "Zurvanite Barding",
  "Stuffed Tsukuyomi",
  "Rainbow Moth Orchid Corsage",
  "Fur-lined Saurian Boots",
  "Moonfire Halter",
  "Missing Pages Orchestrion Roll",
  "Black Triteleia Earring",
  "The Worm's Tail Orchestrion Roll",
  "Adventure Basket",
  "Horde Barding",
  "Taoist's Cap",
  "The Worm's Head Orchestrion Roll",
  "Landlords Orchestrion Roll",
  "Wind-up Aldgoat",
  "Wind-up Garuda",
  "Cropped Summer Indigo Slops",
  "Southern Seas Shoes",
  "The Maker's Ruin Orchestrion Roll",
  "Model Vanguard",
  "Replica Sky Rat Harness of Fending",
  "Red Ribbon",
  "Griffin Leather Cuffs",
  "Uraeus Body Armor",
  "The Black Wolf Stalks Again Orchestrion Roll",
  "White Hyacinth Corsage",
  "Nana Bear",
  "Thavnairian Sarouel",
  "Ramie Poncho",
  "Replica Sky Pirate's Coat of Maiming",
  "Nightbloom Orchestrion Roll",
  "Your Answer Orchestrion Roll",
  "Rainbow Hydrangea Corsage",
  "Ambient Abyss Orchestrion Roll",
  "The Corpse Hall Orchestrion Roll",
  "Woe that Is Madness Orchestrion Roll",
  "Wind-up Qiqirn",
  "Thavnairian Bolero",
  "Falconer's Bottoms",
  "Wind-up Magnai",
  "Adventuring Sweater",
  "Blue Moth Orchid Corsage",
  "Tidal Barding",
  "Hive Barding",
  "Quaintrelle's Dress Shoes",
  "Revenge of the Horde Orchestrion Roll",
  "Wind-up Ifrit",
  "Wind-up Dullahan",
  "Sephirotic Barding",
  "Wind-up Leviathan",
  "White Moth Orchid Corsage",
];

const levelOneShop = [
  "Boulevardier's Ruffled Shirt",
  "Quaintrelle's Ruffled Skirt",
  "Cape of Happiness",
  "High House Justaucorps",
  "Wristlet of Happiness",
  "Coeurl Beach Halter",
  "Summer Indigo Shirt",
  "Boots of Happiness",
  "Against the Wind Orchestrion Roll",
  "Close to the Heavens Orchestrion Roll",
  "Blissful Barding",
  "Levin Barding",
  "Answer on High Orchestrion Roll",
  "Orthodox Barding",
  "Ice Barding",
  "Black and White Orchestrion Roll",
  "Skylords Orchestrion Roll",
  "Landlords Orchestrion Roll",
  "Boots of Happiness",
  "Calfskin Rider's Shoes",
  "Engage Orchestrion Roll",
  "From the Ashes Orchestrion Roll",
  "Blood for Blood Orchestrion Roll",
  "Sophic Barding",
  "Shaded Spectacles",
  "Lost in the Clouds Orchestrion Roll",
  "Starved Orchestrion Roll",
  "Hose of Happiness",
  "Calfskin Rider's Cap",
  "The Silent Regard of Stars Orchestrion Roll",
  "Innocence Barding",
  "Frontier Pumps",
  "Odder Otter Wall Lantern",
  "Calfskin Rider's Bottoms",
  "Calfskin Rider's Jacket",
  "Emerald Barding",
  "Non La",
  "Thunderer Orchestrion Roll",
  "Diamond Barding",
  "Eternal Wind - Shadowbringers Orchestrion Roll",
  "Southern Seas Trousers",
  "Magicked Bed",
  "Barding of Eternal Darkness",
  "Urban Boots",
  "Frontier Trousers",
  "Barding of Divine Light",
  "Titania Barding",
  "Rebel Boots",
  "Frontier Jacket",
  "Company Tabard",
];

const sixOneRegs = [
  "Eblan Danburite",
  "Hannish Fiber",
];
const sixOneShit = [
  "Bluefeather Astrolabos",
  "Bluefeather Barding",
  "Varsity Shoes",
  "Varsity Flat Cap",
  "Varsity Jacket",
  "Buttoned Varsity Jacket",
  "Varsity Bottoms",
  "Varsity Skirt",
  "The Final Day Orchestrion Roll",
  "With Hearts Aligned Orchestrion Roll",

];
const shitThatSells = [
  "Frontier Trousers",
  "Rebel Boots",
  "Southern Seas Trousers",
  "Calfskin Rider's Jacket",
  "Coeurl Beach Halter",
  "Quaintrelle's Ruffled Skirt",
  "Boulevardier's Ruffled Shirt"
];
const temp = [
  "With Hearts Aligned Orchestrion Roll",
  "The Final Day Orchestrion Roll",
];

async function bootstrap() {
  const amount = 1;
  const items = getItems(temp);

  items.forEach(i => i.amount = amount);

  const profits = (await calculateProfit(items));
  const shoppingList = [];
  for (const profit of profits) {
    shoppingList.push(await calculateCraftingPrice({ id: profit.crafted.id, name: profit.crafted.name, amount }));
  }
  await calculateRoute(shoppingList);
}


bootstrap();